name: decoratable_text
description: Decorate a part of the text, such as changing the style and setting a tap action.
version: 0.2.0
homepage: https://github.com/saccho/decoratable_text

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
